//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mnham_mnham.Estab
{


    public partial class Edit
    {
        protected global::System.Web.UI.WebControls.GridView gvMenu;
    }
}
